server:
  shutdown: graceful
  servlet:
    session:
      cookie:
        # 必须配置，防止使用spring-session做session管理时导致相互间session不一致
        name: APP-SESSION-ID
  error:
    include-exception: on
    include-message: always
    whitelabel:
      enabled: off
    path: /error
spring:
  application:
    name: init-template
  #  https://docs.spring.io/spring-boot/docs/3.2.0/reference/htmlsingle/#features.spring-application.virtual-threads
  threads:
    virtual:
      enabled: on
  profiles:
    active: @env@
  jackson:
    time-zone: UTC
    serialization:
      write-enums-using-to-string: on
      write-dates-as-timestamps: off
      fail-on-empty-beans: off
    default-property-inclusion: always
    deserialization:
      fail-on-unknown-properties: off
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
  messages:
    basename: messages/lang
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
      enabled: on
  main:
    banner-mode: off
    keep-alive: on
  mvc:
    log-request-details: on
    async:
      request-timeout: ${ASYNC_REQUEST_TIMEOUT:PT3S}
    # spring-boot 2.2版本后要手动开启form的_method对delete和put的处理
    hiddenmethod:
      filter:
        enabled: on
    static-path-pattern: /static/**
  task:
    scheduling:
      pool:
        size: 40
      thread-name-prefix: asyncScheduleTask-
      shutdown:
        await-termination: on
        await-termination-period: PT3M
    execution:
      pool:
        max-size: 30
        core-size: 10
        queue-capacity: 80
        keep-alive: 600s
      thread-name-prefix: asyncTask-
      shutdown:
        await-termination: on
        await-termination-period: PT3M
  datasource:
    url: ${DB_URL}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      connection-timeout: 30000
      read-only: off
      minimum-idle: ${DATASOURCE_MINIMUM_IDLE:2}
      maximum-pool-size: ${DATASOURCE_MAXIMUM_POOL_SIZE:10}
      auto-commit: on
      max-lifetime: 600000
      idle-timeout: 300000
      connection-test-query: select 1
      validation-timeout: 1500
      pool-name: ${spring.application.name}-HikariCP
config:
  default-timezone: ${APP_TIMEZONE:spring.jackson.time-zone}
  default-datetime-pattern: ${APP_DATETIME_PATTERN:spring.jackson.date-format}
  logging:
    structured: ${LOGGING_STRUCTURED:off}
